using Test
using AnalyticBandRadiation
using Dates

@testset "AnalyticBandRadiation" begin
    include("test_planck.jl")
    include("test_absorption.jl")
    include("test_williams_longwave.jl")
    include("test_shortwave.jl")
    include("test_zenith.jl")
    include("test_rtc.jl")
    include("test_runtime_interfaces.jl")
    include("test_cloudless_longwave_solver.jl")
    include("test_cloudless_shortwave_solver.jl")
    include("test_cloud_optics.jl")
    include("test_cloud_scattering_table.jl")
    include("test_ecckd_definition.jl")
    include("test_ecckd_artifacts.jl")
    include("test_ecckd_ncdatasets_ext.jl")
    include("test_ecckd_model_inventory.jl")
    include("test_ecckd_recovery_metrics.jl")
    include("test_ecckd_teacher_student_recovery.jl")
    include("test_ecckd_teacher_student_recovery_scan.jl")
    include("test_ecckd_band_accuracy_pareto.jl")
    include("test_ecckd_objective_reconstruction_check.jl")
    include("test_ecckd_published_training_manifest.jl")
    include("test_ckdmip_training_data_download_plan.jl")
    include("test_ckdmip_training_data_preflight.jl")
    include("test_ecckd_derived_flux_generation_plan.jl")
    include("test_concat_ckdmip_flux_chunks.jl")
    include("test_ckdmip_download_script.jl")
    include("test_ecckd_official_files_check.jl")
    include("test_ecckd_forward.jl")
    include("test_rrtmgp_ext.jl")
    include("test_metrics.jl")
    include("test_access_points_check.jl")
    include("test_ecrad_reference_manifest.jl")
    include("test_ecrad_materialize_references.jl")
    include("test_ecrad_candidate_schema.jl")
    include("test_ecrad_accuracy_gate.jl")
    include("test_ecrad_cloudless_accuracy_gate.jl")
    include("test_ecrad_accuracy_diagnostics.jl")
    include("test_ecrad_flux_bias_diagnostics.jl")
    include("test_ecrad_all_sky_cloud_effect_diagnostics.jl")
    include("test_ecrad_all_sky_cloud_sweep.jl")
    include("test_ecrad_all_sky_optics_gap.jl")
    include("test_ecrad_cloud_scattering_tables_check.jl")
    include("test_ecrad_all_sky_ifs_gate.jl")
    include("test_reduced_ecckd_subset_search.jl")
    include("test_reduced_ecckd_size_scan.jl")
    include("test_ecckd_32b_baseline_check.jl")
    include("test_reduced_ecckd_metadata.jl")
    include("test_reduced_ecckd_32g_rrtmgp_comparison.jl")
    include("test_reduced_ecckd_gap_report.jl")
    include("test_reduced_ecckd_optical_depth_fit_preflight.jl")
    include("test_reduced_ecckd_optimization_preflight.jl")
    include("test_reduced_ecckd_constrained_table_optimizer.jl")
    include("test_reduced_ecckd_pressure_band_refinement_preflight.jl")
    include("test_official_ecckd_training.jl")
    include("test_goal_audit_check.jl")
    include("test_recovery_goal_audit.jl")
end

@testset "SpeedyWeather Extension" begin
    include("test_with_speedyweather.jl")
end
